spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geozentra
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        jdbc:
          fetch_size: 10

  sql:
    init:
      mode: never

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/geointelli

  flyway:
    enabled: false
    # baseline-on-migrate: true
    # baseline-version: 1
server:
  port: 8081
  
logging:
  level:
    root: INFO
    com:
      geointelli: DEBUG
    org:
      springframework: WARN
      hibernate: WARN # DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"  
  file:
    name: /logs/springboot.log   