spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geointelli
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        jdbc:
          fetch_size: 10

  sql:
    init:
      mode: never

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/geointelli

server:
  port: 8081
  