spring:
  application:
    name: geointelli

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 8080

aws:
  region: ${AWS_REGION}
  access_key: ${AWS_ACCESS_KEY}
  secret_key: ${AWS_SECRET_ACCESS_KEY}

  s3:
    bucket: geozentra-images-prod-286528690180-us-east-1-an